---
title: "DSPN expression analysis"
author: "Phong N."
date: "23 Nov, 2020"
output:
  html_document:
    toc: true
    toc_float: true
    code_folding: hide
---

```{r setup, include=FALSE}
library(ggplot2)
library(tidyr)
library(dplyr)
library(knitr)
library(xtable)
library(cowplot)
library(stringr)
library(effsize)
library(scales)
library(ggrepel)
library(ggpubr)
library(RColorBrewer)
library(broom)
library(Hmisc)
library(limma)
library(DESeq2)
library(ComplexHeatmap)
library(haven)
library(ConsensusClusterPlus)
library(factoextra)
library(dendextend)
library(illuminaHumanv3.db)
library(VennDiagram)
library(topGO)
library(org.Hs.eg.db)
library(outliers)
knitr::opts_chunk$set(xtable.comment = FALSE, 
                      echo=T,
                      eval=T, 
                      message = F,
                      warning=F, 
                      error = F,
                      cache = F, 
                      tidy = F, 
                      size="footnotesize",
                      fig.pos='H',
                      results='markup',
                      fig.lp='fig:',
                      fig.align = 'center',
                      fig.path='figures/example-', 
                      cache.path = 'cache/example-',
                      tidy.opts=list(width.cutoff=80)
                     )
options(xtable.comment = FALSE)
```

### Data processing
```{r}
dat = read.csv("KORA_F4_993_samples_Expressionsdaten.csv",header = T,
                    check.names = F,row.names = 1) %>% as.matrix()
gene.an = read.csv("Annotation_HumanHT-12v3_final.csv",check.names = F,sep = "\t")
gene.an = gene.an %>% 
  mutate(symbol = unlist(mget(gene.an$Probe_Id,illuminaHumanv3SYMBOL)),
         EntrezID = unlist(mget(gene.an$Probe_Id,illuminaHumanv3ENTREZID)),
         gene = unlist(mget(gene.an$Probe_Id,illuminaHumanv3GENENAME)))
gene.an$symbol = ifelse(is.na(gene.an$symbol), gene.an$ILMN_Gene, gene.an$symbol)
drop = gene.an$Probe_Id[gene.an$`QC comment`=="bad [no matched mRNA]" | is.na(gene.an$symbol)]
clin <- read_sas("gesamt_k05720g_v2007.sas7bdat", NULL) %>% filter(!is.na(utmnsi))
tech = read.table("KORA_F4_technical_variables.txt", sep = "", header = T)
info = tech %>% mutate(mnsi = clin$utmnsi[match(.$ZZ.NR,clin$un_expr_f4ogtt)])
info = na.omit(info)
# info$mnsi.bi.1 = ifelse(info$mnsi > 1, "high", "low")
# info$mnsi.bi.2 = ifelse(info$mnsi > 2, "high", "low")
# info$mnsi.bi.3 = ifelse(info$mnsi > 3, "high", "low")
# info$mnsi.bi.4 = ifelse(info$mnsi > 4, "high", "low")
# info$mnsi.bi.5 = ifelse(info$mnsi > 5, "high", "low")
# info$mnsi.bi.6 = ifelse(info$mnsi > 6, "high", "low")
dat.fil = dat[ !rownames(dat) %in% drop ,as.character(info$ZZ.NR)]
symbol = gene.an$symbol[match(rownames(dat.fil),gene.an$Probe_Id)]
dat.fil = avereps(dat.fil,symbol)
str(dat.fil)
design = model.matrix(~ 0 + mnsi, data=info)
dat.nobatch = removeBatchEffect(x=dat.fil, 
                                design = design,
                                batch = info$p_amplification,
                                covariates = info[,c("RIN","sample_storage_time")])

meansd = data.frame(mean = apply(dat.nobatch,1,mean), sd = apply(dat.nobatch,1,sd), 
                    iqr = apply(dat.nobatch,1,IQR))
ggplot(meansd, aes(x=mean,y=sd))+
  geom_point(col = "black",alpha=0.5)+
  stat_smooth(method = "loess",se=F,col="red")
```

### Hierarchical clustering

```{r, fig.width=6, fig.height=4}
hist(info$mnsi, breaks = 15, xlab = "MNSI score",main = "MNSI score distribution")
dat.topvar = dat.nobatch[rownames(meansd[meansd$iqr>quantile(meansd$iqr,0.9),]),]
meansd.topvar = meansd[rownames(dat.topvar),]
dat.topvar.z = apply(dat.topvar,2,function(x) (x-meansd.topvar$mean)/meansd.topvar$sd)
```

```{r, fig.width=10, fig.height=7}
column_an = HeatmapAnnotation(MNSI = info$mnsi
                              # ,MNSI_1 = info$mnsi.bi.1,
                              # MNSI_2 = info$mnsi.bi.2,
                              # MNSI_3 = info$mnsi.bi.3,
                              # MNSI_4 = info$mnsi.bi.4,
                              # MNSI_5 = info$mnsi.bi.5,
                              # MNSI_6 = info$mnsi.bi.6
                              )
Heatmap(dat.topvar.z, cluster_rows = T, cluster_columns = T, show_column_names = F,
        show_row_names = F, name = "Z score",row_title = "Genes", top_annotation = column_an,
        column_title = "Samples", column_title_rot = 0, clustering_method_columns = "ward.D2")
```

### Dimensional reduction
```{r}
pca = prcomp(t(dat.topvar), scale. = T)
pca_df = data.frame(pca$x, info)
pca_var = summary(pca)$importance
varp = round(pca_var[2,]*100,2)
ggplot(pca_df,aes(x=PC1,y=PC2,col = RIN)) + 
  geom_point(size = 3, alpha = 0.5)+
  xlab(paste("PC1 (",varp[1],"%)")) +
  ylab(paste("PC2 (",varp[2],"%)")) +
  theme(panel.background = element_rect(fill = "white"))
ggplot(pca_df,aes(x=PC1,y=PC3,col = p_amplification)) + 
  geom_point(size = 3, alpha = 0.5)+
  xlab(paste("PC1 (",varp[1],"%)")) +
  ylab(paste("PC3 (",varp[3],"%)")) +
  theme(panel.background = element_rect(fill = "white"))

dat.processed = dat.nobatch[,-which(pca_df$PC1 > 300)]
saveRDS(dat.processed, file = "expression_processed.rds")
```

### DE analysis

```{r, eval=F}
cor.mnsi = apply(dat.nobatch,1,function(x) cor(x,info$mnsi,method = "pearson"))
hist(cor.mnsi, main = "Correlation of GEx and MNSI score", xlab = "Pearson coefficient")
cor.gene = names(cor.mnsi[abs(cor.mnsi)>=0.1])
cor.gene.df = data.frame(symbol = cor.gene,cor = cor.mnsi[abs(cor.mnsi)>=0.1],
                         name = gene.an$gene[match(cor.gene,gene.an$symbol)])
cor.gene.df
modmatrix2 = model.matrix(~ 0 + mnsi.bi.2, data=info)
fit = lmFit(dat.nobatch,modmatrix2)
head(coef(fit))
contrast = makeContrasts(mnsi.bi.2high - mnsi.bi.2low, levels = colnames(coef(fit)))
contrast
tmp <- contrasts.fit(fit, contrast)
tmp <- eBayes(tmp)
topde <- topTable(tmp, sort.by = "P", n = Inf)
head(topde, 20)

topde = topde %>% mutate(Gene = rownames(topde)) %>% 
  mutate(Entrez = gene.an$EntrezID[match(.$Gene,gene.an$symbol)])
ggplot(topde, aes(x=logFC, y=-log10(P.Value))) +
  geom_point(alpha = 0.3)+
  geom_point(data = filter(topde, adj.P.Val < 0.05), col = "red") +
  geom_text_repel(data = filter(topde, adj.P.Val < 0.05), aes(label = Gene)) +
  theme(panel.background = element_rect(fill = "white"))
```

### Significant genes

```{r, fig.width=10, fig.height=8, eval=F}
topde.sig = filter(topde, adj.P.Val < 0.05)
topde.pl = list()
for (i in 1:nrow(topde.sig)) {
  g = topde.sig$Gene[i]
  df = info %>% mutate(expr = dat.nobatch[g,])
  p = ggplot(df, aes(x=mnsi.bi.2, y=expr)) +
    geom_violin(scale = "count", draw_quantiles = 0.5)+
    xlab("MNSI score")+
    ggtitle(label = g)
  topde.pl[[i]] = p
}
plot_grid(plotlist = topde.pl, nrow = 5)
```

### Gene set enrichment analysis

```{r, eval=F}
sig.gene = topde$adj.P.Val
names(sig.gene) = topde$Entrez
topDiffGenes<-function(x){ return(x<=0.05) }
topgo = new("topGOdata",
          ontology="BP",
          allGenes=sig.gene, #named vector with adj. p-values
          geneSel=topDiffGenes,
          annot=annFUN.org,
          nodeSize = 10, #minimum number of genes in a GO categorie,
          ID="Entrez",
          mapping="org.Hs.eg.db")
numGenes(topgo)
numSigGenes(topgo)
fisher.res<-runTest(topgo, algorithm="elim",
                    statistic="fisher")
fisher.res
fisher.tab <- GenTable(topgo, Fisher=fisher.res, orderBy="Fisher", topNodes = geneData(fisher.res)[4])
kable(head(fisher.tab, n=10))
```

